### ISSUE TITLE
sq inspect should offer a flag to only show summary metadata

### ISSUE THREAD

**Issue by neilotoole** [neilotoole/sq#264]
**Is your feature request related to a problem? Please describe.**

`sq inspect` will shows schema metadata (tables, etc). This is as expected. However, it's sometimes the case that we just want to see the "summary" metadata. Here's the current output of `sq inspect -y`:

```yaml
handle: "@sakila/pg12"
location: postgres://sakila:xxxxx@192.168.50.132/sakila
name: sakila
name_fq: sakila.public
schema: public
driver: postgres
db_driver: postgres
db_product: PostgreSQL 12.13 on x86_64-pc-linux-musl, compiled by gcc (Alpine 12.2.1_git20220924-r4) 12.2.1 20220924, 64-bit
db_version: "12.13"
user: sakila
size: 17613679
table_count: 29
tables:
- name: actor
  name_fq: sakila.public.actor
  table_type: table
  table_type_db: BASE TABLE
  row_count: 200
  size: 73728
```

A particular use case for this is when the user submits a bug. It would be good to be able to see the metadata, without the schema info (which may contain sensitive info).

**Describe the solution you'd like**

There should be a flag `--summary` or `--no-schema` that omits the `tables` field. E.g. the output of `sq inspect --yaml --summary` might be:

```yaml
handle: "@sakila/pg12"
location: postgres://sakila:xxxxx@192.168.50.132/sakila
name: sakila
name_fq: sakila.public
schema: public
driver: postgres
db_driver: postgres
db_product: PostgreSQL 12.13 on x86_64-pc-linux-musl, compiled by gcc (Alpine 12.2.1_git20220924-r4) 12.2.1 20220924, 64-bit
db_version: "12.13"
user: sakila
size: 17613679
```
