### ISSUE TITLE
Inconsistent decimal handling

### ISSUE THREAD

**Issue by neilotoole** [neilotoole/sq#335]
**Describe the bug**

`sq` doesn't handle decimal values correctly. It probably treats them as `float64`, which leads to unexpected results.

See this workflow run: https://github.com/neilotoole/sq/actions/runs/6932116521/job/18855333269#step:6:2345

```
    db_type_test.go:194: 
        	Error Trace:	D:/a/sq/sq/drivers/sqlite3/db_type_test.go:194
        	Error:      	Not equal: 
        	            	expected: "77.77"
        	            	actual  : "77.77000000000001"

```

**To Reproduce**

Seems to happen intermittently in workflows.

**Expected behavior**

In the example above, `77.77` should always be returned, never `77.77000000000001`

**`sq` version**

Paste the output of `sq version --yaml` into the code block below:

```yaml
# $ sq version --yaml
version: v0.44.0
commit: 69d5402
timestamp: 2023-11-20
latest_version: v0.44.0
host:
  platform: darwin
  arch: arm64
  kernel: Darwin
  kernel_version: 22.6.0
  variant: macOS
  variant_version: 13.6.2
```

**Source details**

The workflow example above is with `sqlite`, but it may happen elsewhere.

**Additional context**

The problem is almost certainly that `sq` is using `float64` to store decimal values, when it really needs to use a dedicated decimal type, e.g. [`shopspring/decimal`](https://github.com/shopspring/decimal).

- https://github.com/go-sql-driver/mysql/issues/1177
- https://github.com/golang/go/issues/30870
- https://github.com/shopspring/decimal
